### ISSUE TITLE
[FEAT] improve the text section UI

### ISSUE THREAD

**Issue by starlightknown** [starlightknown/thankful.ly#13]
the UI for sending text message is very minimal and can be improved. 
![image](https://user-images.githubusercontent.com/74637789/157029225-5048016e-e27c-4895-93db-7cd7c58f1ca2.png)

to get started navigate to the folder `sendmessage.html`

**Comment by bhavya-sj** [comment]
can you assign this to me

**Comment by komalhadimani4444** [comment]
Assign me this ma'am

**Comment by starlightknown** [comment]
Done
