### ISSUE TITLE
Improve the title of Webpage

### ISSUE THREAD

**Issue by ashwinexe** [starlightknown/thankful.ly#7]
The title can be improved/beautified 
![image](https://user-images.githubusercontent.com/53075480/136068814-f4ea3a6d-2eac-42c1-8975-8c5de591dac0.png)

Instructions to contribute:
- [ ] Fork the repository
- [ ] clone the forked repository
- [ ] make the necessary changes on a new branch named `issue #7`
- [ ] Create a pull request

**Comment by amisha123prajapati** [comment]
Hello Maintainers,
What we have to write at the place of old title? You will suggest title name or we have to write from ourself?

**Comment by ashwinexe** [comment]
@amisha123prajapati the title should be the same `Thankful.ly` you have to beautify it so it looks good on the page

**Comment by ssurbhi09** [comment]
U can use *_name you want_* it Chang your font style
Also u use *name u want* thankyou

**Comment by amisha123prajapati** [comment]
Okay,got it.

**Comment by ssurbhi09** [comment]
Ap kise bol rhe
And jis section mai ye topic wali portion
 Hai if u want then u can assign me I can change the font

**Comment by amisha123prajapati** [comment]
I am biginner student in hacktoberfest,so can you guide me step by step what i have to do then i will sure do it.

**Comment by SrinivasJoshi** [comment]
@ashwinexe  I would interested in changing the title and contributing more to UI/UX of the application.

**Comment by ashwinexe** [comment]
@amisha123prajapati assigned. good luck. follow the updated steps mentioned in the issue. If you have any issues ask here :)

**Comment by amisha123prajapati** [comment]
@ashwinexe  in how many time i have to complete it ,any deadline or it depends on me?

**Comment by ashwinexe** [comment]
> @ashwinexe in how many time i have to complete it ,any deadline or it depends on me?

It's an easy issue that can be done in a day or two. I'd prefer not to stay on the issue more than a week.

**Comment by amisha123prajapati** [comment]
Please assign again to me by mistake i clicked on unassign

**Comment by amisha123prajapati** [comment]
I want to work on it

**Comment by amisha123prajapati** [comment]
Thankyou

**Comment by amisha123prajapati** [comment]
@ashwinexe 
https://drive.google.com/file/d/10_rjxAiLklHclCS6cxDzbpCr7feXyrDX/view?usp=drivesdk

Please check it now its looking good or i have to beautify anything more,

Now can i create pull request?

**Comment by amisha123prajapati** [comment]
I have created a PR , now what we have to do?

**Comment by amisha123prajapati** [comment]
@ashwinexe please reply

**Comment by ashwinexe** [comment]
Merged, thanks for contributing 👍

**Comment by amisha123prajapati** [comment]
Thankyou
